### ISSUE TITLE
Error when running tutorial

### ISSUE THREAD

**Issue by yrq3027** [isayevlab/Auto3D_pkg#37]
Hi! I cannot get result file when run the tutorial.ipynb with followed error. Can you help me, thank you!
Isomer generation for job1
Enumerating cis/tran isomers for unspecified double bonds...
Enumerating R/S isomers for unspecified atomic centers...
Removing enantiomers...
Enumerating conformers/rotamers, removing duplicates...
100%|███████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 110.89it/s]
Process Process-4:
Traceback (most recent call last):
  File "C:\Users\yuanrong.fan\AppData\Local\miniconda3\envs\auto3D\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\yuanrong.fan\AppData\Local\miniconda3\envs\auto3D\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yuanrong.fan\AppData\Local\miniconda3\envs\auto3D\lib\site-packages\Auto3D\auto3D.py", line 114, in isomer_wraper
    engine.run()
  File "C:\Users\yuanrong.fan\AppData\Local\miniconda3\envs\auto3D\lib\site-packages\Auto3D\isomer_engine.py", line 239, in run
    self.combine_SDF(self.rdk_tmp, self.enumerated_sdf)
  File "C:\Users\yuanrong.fan\AppData\Local\miniconda3\envs\auto3D\lib\site-packages\Auto3D\isomer_engine.py", line 192, in combine_SDF
    mols = pybel.readfile('sdf', file)
  File "C:\Users\yuanrong.fan\AppData\Local\miniconda3\envs\auto3D\lib\openbabel\pybel.py", line 159, in readfile
    raise ValueError("%s is not a recognised Open Babel format" % format)
ValueError: sdf is not a recognised Open Babel format

**Comment by LiuCMU** [comment]
Hi, can you check your Open Babel version?

 `conda list openbabel`

it should be at least `3.x`

**Comment by yrq3027** [comment]
Thank you. OPenbabel is 3.1.1. I use the windows system,should I change?

**Comment by LiuCMU** [comment]
Hi, this is interesting. SDF should be a readable format for pybel 🤔 

Are you running the `tutorial.ipynb` as is? 

Auto3D runs on different OS. I tested it on Windows a while ago. But if you have access to a linux/unix system, could you try to run `tutorial.ipynb` to see if the problem persists? thanks!

**Comment by yrq3027** [comment]
Hi, it worked on ubuntu with docker. I cannot successful install openbabel on windows
