### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by SawanKumar23** [isayevlab/Auto3D_pkg#87]
**Describe the bug**
I have been using auto3d to generate 3d structures from a sdf file containing 134 structures. Every step is executed, but at last, it shows EOFError. 

auto3d parameters.yaml 

         _              _             _____   ____  
        / \     _   _  | |_    ___   |___ /  |  _ \ 
       / _ \   | | | | | __|  / _ \    |_ \  | | | |
      / ___ \  | |_| | | |_  | (_) |  ___) | | |_| |
     /_/   \_\  \__,_|  \__|  \___/  |____/  |____/  2.3.1
        // Automatic generation of the low-energy 3D structures                                      
    
Checking input file...
	There are 134 conformers in the input file /media/niper/data1/Sawan_PhD_2024/success.sdf. 
	All conformers and IDs are valid.
Suggestions for choosing isomer_engine and optimizing_engine: 
	Isomer engine options: RDKit and Omega.
	Optimizing engine options: AIMNET or your own NNP.
The available memory is 16 GB.
The task will be divided into 1 jobs.
Job1, number of inputs: 134

Isomer generation for job1
100%|█████████████████████████████████████████| 134/134 [00:06<00:00, 22.30it/s]

Optimizing on job1
Preparing for parallel optimizing... (Max optimization steps: 5000)
Total 3D conformers: 410
 10%|███▉                                    | 499/5000 [05:49<22:53,  3.28it/s]Total 3D structures: 410  Converged: 284   Dropped(Oscillating): 0    Active: 126
 20%|███████▉                                | 999/5000 [07:14<08:53,  7.50it/s]Total 3D structures: 410  Converged: 388   Dropped(Oscillating): 0    Active: 22
 30%|███████████▋                           | 1499/5000 [08:20<07:41,  7.59it/s]Total 3D structures: 410  Converged: 401   Dropped(Oscillating): 3    Active: 6
 40%|███████████████▌                       | 1999/5000 [09:25<06:23,  7.83it/s]Total 3D structures: 410  Converged: 404   Dropped(Oscillating): 5    Active: 1
 45%|█████████████████▍                     | 2235/5000 [09:55<12:16,  3.75it/s]
Optimization finished at step 2236:   Total 3D structures: 410  Converged: 404   Dropped(Oscillating): 6    Active: 0
Begin to select structures that satisfy the requirements...
Energy unit: Hartree if implicit.
Program running time: 13 minute(s)
Traceback (most recent call last):
  File "/home/niper/miniforge3/envs/auto3d/bin/auto3d", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/home/niper/miniforge3/envs/auto3d/lib/python3.13/site-packages/Auto3D/auto3Dcli.py", line 166, in cli
    out = main(arguments)
  File "/home/niper/miniforge3/envs/auto3d/lib/python3.13/site-packages/Auto3D/auto3D.py", line 450, in main
    path_output = decode_ids(path_combined, mapping)
  File "/home/niper/miniforge3/envs/auto3d/lib/python3.13/site-packages/Auto3D/utils_file.py", line 312, in decode_ids
    new_name = mapping[int(name)]
               ~~~~~~~^^^^^^^^^^^
KeyError: 12
Process Process-3:
Traceback (most recent call last):
  File "/home/niper/miniforge3/envs/auto3d/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/niper/miniforge3/envs/auto3d/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niper/miniforge3/envs/auto3d/lib/python3.13/site-packages/Auto3D/auto3D.py", line 259, in logger_process
    message = queue.get()
  File "<string>", line 2, in get
  File "/home/niper/miniforge3/envs/auto3d/lib/python3.13/multiprocessing/managers.py", line 824, in _callmethod
    kind, result = conn.recv()
                   ~~~~~~~~~^^
  File "/home/niper/miniforge3/envs/auto3d/lib/python3.13/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/niper/miniforge3/envs/auto3d/lib/python3.13/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
  File "/home/niper/miniforge3/envs/auto3d/lib/python3.13/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError




**System information:**
 - Operating System: Ubuntu 22.04.5 LTS
- Auto3D version: 2.3.1
- Python version: 3.13
- RDKit version: 2024.9.1
- PyTorch version: torch-2.4.1.post302

**Comment by ilkwonch** [comment]
test with small subset of input structures to ensure if the sdf inputs have correct ids, geometries
